	  
name: GitHub Actions Demo
run-name: Run ${{ github.run_number }} triggered by ${{ github.event_name }} event
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
