name: GitHub Actions Demo
run-name: Run ${{ github.run_number }} triggered by ${{ github.event_name }} event
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print variable
        run: echo ${{ vars.GH_TOKEN }}
